### ISSUE TITLE
Tendermint tmlibs and common dependencies

### ISSUE THREAD

**Issue by silasdavis** [tendermint/iavl#46]
tmlibs and common are core dependencies of Tendermint containing a lot of somewhat independent code. Aggregating this code does make a lot of sense for versioning Tendermint, but for other projects like this one creates an undesirable level of coupling that could be avoided. I would like to propose that we drop the dependency on both. This would make it possible to upgrade Tendermint and iavl independently without forcing an upgrade of one or the other, which is the issue I am running into. I would argue that the code dependencies that iavl has on tmlibs and common are trivial, and particularly in the latter case is not pulling its weight.

tmlibs is currently imported for a subset of the `DB` interface and `NewMemDB`. This is convenient but means we pull in an entire dependency of tmlibs which makes it hard to use independently with Tendermint. Instead we could replicate the portion of the DB interface we need (`Get`, `Set`, `NewBatch`, and `Iterator`). `MemDB` is pretty trivial and the implementation against this subset interface would be even easier. This also adds a significant advantage for extensibility and mocking int that `NodeDB` would only be asking for what it actually needs - which is not the entire `DB` interface (e.g. https://blog.chewxy.com/2018/03/18/golang-interfaces/). I think this combined with decoupling from Tendermint/tmlibs is probably a good enough reason to accept the small amount of duplication. Admittedly iavl _does_ depend on the semantics of the `DB` interface, but I think we could make clear that you may want use tmlibs in your iavl-based application - you would also have the flexibility to use a previous version with this subset interface (I think - and if not it would easier to make an adapter).

common is used for `HexBytes`, `RandStr`, `Fmt`, and `PanicSanity`. I think this is one of those cases where being DRY is the wrong thing to do. These are all relatively low value methods and don't seem to me to justify the dependency. They could either be replicated or removed. I feel like `HexBytes` is a convention that should belong to parent projects, `RandStr` introduces non-determinism into the unit tests which is not ideal, and `Fmt` and `PanicSanity` add very little.

**Comment by ebuchman** [comment]
I'm in strong agreement.

Would you be open to make a PR to remove the dependencies?

Only thing is that it should be made very clear that the expect dbs come from tmlibs/db, but it shouldn't be a problem to replicate the parts of the interface we need and the MemDB itself within this repo.

**Comment by jaekwon** [comment]
<open debate>

IAVL debugging benefits much from the DB module's debugging facilities.
The DB interfaces are stable and useful.  We should use more of it and decouple *it* from tmlibs.  The pain is partially due to us packaging many dependencies together.  As packages (like db) mature I think we should move the out, and db is ripe.  (it benefited by being developed in tandem with the SDK and Tendermint, so I'm not knocking tmlibs in any way).

I'd extend Dave's blog post with useful entangled interface sets like our tmlibs/db or https://golang.org/pkg/crypto/ . They are most useful/ergonomic when entangled (for as long as they are well designed and consistent), and they don't suffer from the smells that he's talking about.

**Comment by silasdavis** [comment]
To add to this now IAVL has a dependency on Tendermint - for tendermint/libs/common and tendermint/crypto/tmhash. This is quite painful for upgrades since I dep now wants me to have compatible tendermint and IAVL versions.

It looks like this dependency is mostly for errors.Wrap and some straight-forward hash conventions that I feel could easily be copied. Is it really worth the dependency?

**Comment by ValarDragon** [comment]
Spinning of this db stuff is a fairly large design choice, we have chosen to adopt the monorepo style for better utilization of developer time. This would mean breaking off from it. We were actually discussing moving IAVL to the Cosmos-SDK as well. 

If the DB stuff is very stable, I'm not opposed to this though.

**Comment by silasdavis** [comment]
Personally I would like to see IAVL remain a separate library, but it is the worst of all worlds to have it in a separate repo but have dependencies on something has a heavy as Tendermint, so I suppose if that is the way it goes it would make sense to roll it into the cosmos-sdk.

It was a nightmare having half a dozen dependency libraries I agree, and particularly since in reality only Tendermint depended on them - they weren't mature and moved too quickly for that to make sense. So stability is one factor, but another one is if you genuinely have multiple independent things depending on a library. For the db libs you currently have at least: Tendermint, Burrow, IAVL, and the cosmos-sdk.

As @jaekwon says above:

> The pain is partially due to us packaging many dependencies together. As packages (like db) mature I think we should move the out, and db is ripe.

I'm inclined to agree. I don't think the DB is necessarily 'very stable' - everything that depends on it is in principle alpha software! However I do think it is relatively more stable and it has real dependencies (and could attract more as a key-value db abstraction layer if maintained separately from Tendermint which I think would be for the good).

**Comment by ebuchman** [comment]
Probably would be good to see `db` move into its own repo soon, though impending changes are

- possible issues with ReverseIterator (https://github.com/cosmos/cosmos-sdk/issues/2243)
- experimenting with backends to improve performance (https://github.com/tendermint/tendermint/pull/2337, https://github.com/tendermint/tendermint/pull/2370).

Recently there's been some consideration around moving IAVL to tendermint actually, but I think for now it will stay independent. After a bit more work on the `db`, I think we can consider spinning it out on its own.

Meanwhile, would be great to see IAVL otherwise reduce its dependencies.

**Comment by marbar3778** [comment]
Update: the only thing that is being used from `tendermint/tendermint` now is crypto, hopefully in the near future we can remove this as well.

**Comment by marbar3778** [comment]
for the time being, we will keep tendermint as a dep because of  `tendermint/crypto`, if you want it to be entirely removed, please reopen this issue
